### ISSUE TITLE
Command output remains visible on successful validation when saving.

### ISSUE THREAD

**Issue by MokoJumbie** [natesilva/jshint-external.tmbundle#1]
This assumes the command output is docked to the window

Steps to reproduce:
-Save and validate .js file
-Errors show in command output
-Fix all errors, but leave command output open
-Save and validate .js file again
-Validation is successful but command output remains open with no feedback, leaving user unsure of result.

Possible expected behaviours on successful validation:
-command output always appears on save instead of only on validation failure.
-if command output is visible, update it with success message, otherwise don't show it (current behaviour)
-if command output is visible and contains output from last jshint-execution, close it

**Comment by natesilva** [comment]
Definitely needs to be fixed. Something like your second suggestion sounds ideal:

> -if command output is visible, update it with success message, otherwise don't show it (current behaviour)

The problem is that I don’t know how to detect if TextMate is currently showing the validation output. I need to look into that.

Your first suggestion:

> -command output always appears on save instead of only on validation failure.

...would be easy to implement, but IMO it would be too annoying to always have the validation window pop up.
